iterative ref: build_ctf_array
compSPI/reconstructSPI pull request #48
Opened 2022-04-07 07:53 UTC by jedyeo

Design choice that needs to be discussed!

We propose `self.ctf_info` to instead be a singular dictionary instead of a list of dicts. `ctf_info` would contain CTF config values, and contain an additional key, `ctf_params`, which holds 3 key-value pairs. The keys would be the defocus u, v, angles, and the values would be an ordered list (with each index corresponding to a particle).

```
self.ctf_info = {   
            'amplitude_contrast': 0.1,
            'b_factor': 0.0,
            'batch_size': len(self.particles),  # num samples
            'cs': 2.7,
            'ctf_size': 32,  # n_pix
            'kv': 300,
            'pixel_size': 3.2,
            'side_len': 32,
            'value_nyquist': 0.1,
            'ctf_params' : {   # user would also pass this part in
                'defocus_u' : [...],
                'defocus_v' : [...],
                'defocus_angle' : [...], 
            }
        }
```

2022-04-07 08:54 UTC, jedyeo commented
Looks like we can't import from `simSPI.linear_simulator` since it's not recognized as a module.

2022-04-07 09:14 UTC, jedyeo commented
im going to rest now and get back to this tmrw morning :)

2022-04-07 19:21 UTC, geoffwoollard commented
Let me look into `value_nyquist`

2022-04-07 19:40 UTC, geoffwoollard commented
Stick to the linear simulator ctf as much as possible, including how the ctf params are passed in. Match the ctf params dictionary in linear_simulator.ctf with how you take in the ctf, so that you don't have to write any parser.

If you don't write code, you don't have to test it!

2022-04-07 19:55 UTC, geoffwoollard commented
> Design choice that needs to be discussed!
> 
> We propose `self.ctf_info` to instead be a singular dictionary instead of a list of dicts. `ctf_info` would contain CTF config values, and contain an additional key, `ctf_params`, which holds 3 key-value pairs. The keys would be the defocus u, v, angles, and the values would be an ordered list (with each index corresponding to a particle).
> 
> ```
> self.ctf_info = {   
>             'amplitude_contrast': 0.1,
>             'b_factor': 0.0,
>             'batch_size': len(self.particles),  # num samples
>             'cs': 2.7,
>             'ctf_size': 32,  # n_pix
>             'kv': 300,
>             'pixel_size': 3.2,
>             'side_len': 32,
>             'value_nyquist': 0.1,
>             'ctf_params' : {   # user would also pass this part in
>                 'defocus_u' : [...],
>                 'defocus_v' : [...],
>                 'defocus_angle' : [...], 
>             }
>         }
> ```
> 
> This follows the required input/output from `linear_simulator.ctf` https://github.com/compSPI/simSPI/blob/master/simSPI/linear_simulator/ctf.py

The "user" is whoever is calling this function. Could be a methods developer or practitioner. Hard to say now since it's early days. This function just reads the ctf params that come from somewhere else and doesn't change them. Don't use default values. In the tests, you'll have to put some values in, and those look like OK values. I would suggest also
* pixel_size: 128 to 256
* defocus_u,defocus_v: 0.5 to 2.5 since it's in um. have their ratio not too far from 1. e.g. 0.9 to 1.1
* angle_astigmatism: 0 to 2pi
* wavelength: 0.1968, which corresponds to 300 kev. Instead of the kv beam energy, linear_simulator.ctf uses the electron wavelength 
  * I think in units of Angstroms, from the docs and tests
  * https://github.com/compSPI/simSPI/blob/master/simSPI/linear_simulator/ctf.py#L50
  * https://github.com/compSPI/simSPI/blob/master/tests/test_ctf.py#L133
  *  1 A = 10 pm. See 300 kev in this table: https://www.jeol.co.jp/en/words/emterms/search_result.html?keyword=wavelength%20of%20electron

I'll also look into ctf_size != side_len. It could be related to zero padding...

2022-04-07 20:01 UTC, geoffwoollard commented
@jedyeo @thisTyler @arjunsingh3600 @calhep you can play with this applet to get some intuition about the CTF
https://3dem.github.io/relion/ctf.html

Good pedagogical post
https://forum.scilifelab.se/t/thinking-about-ctf/114

2022-04-07 20:11 UTC, geoffwoollard commented
You can look at the tests for how `ctf_params` is defined in linear_simulator and how you should therefore construct it in the tests. Take note of all the batches etc. Read up on the tests and docs of https://github.com/compSPI/simSPI/blob/master/simSPI/linear_simulator/ctf.py#L160

2022-04-08 05:44 UTC, geoffwoollard commented on reconstructSPI/iterative_refinement/expectation_maximization.py
> +    ctf_info : dict
I wouldn't repeat. Just say, see *** documentation and point to the place the ctf comes from. that way when it changes there it doesn't need to be updated here.

2022-04-08 05:46 UTC, geoffwoollard commented on reconstructSPI/iterative_refinement/expectation_maximization.py
>          return ctf.get_ctf(tensor_dict).numpy().reshape(ctf_shape)
ok this parser looks good

2022-04-08 05:47 UTC, geoffwoollard commented on reconstructSPI/iterative_refinement/expectation_maximization.py
> +    ctf_info : dict
also the documentation is too restrictive. while these are reasonable/typical values for testing, others outside their range are still valid, even if a bit less common.

2022-04-08 05:47 UTC, geoffwoollard commented on tests/test_expectation_maximization.py
> +    return np.random.uniform(low=0.5, high=2.5, size=(n_particles,))
good for tests

2022-04-08 05:49 UTC, geoffwoollard commented on tests/test_expectation_maximization.py
> +        "kv": 0.1968,
kv could/should be 300. in that case wavelength would be 0.1968.

it's my understanding that `ctf.get_ctf` needs `wavelength` and doesn't use `kv`

2022-04-08 05:52 UTC, geoffwoollard requested changes
Close... but a bit more work needed.

I like the tests... how they have the `n_particles` for defocus etc and work with `test_ir`

2022-04-08 06:51 UTC, geoffwoollard approved these changes
Would be good to show screen shot of what the ctf looks like with these values as sanity check. I'll merge, we'll see downstream.

2022-04-08 06:51 UTC, geoffwoollard commented
Fixes https://github.com/compSPI/reconstructSPI/issues/11

2022-04-08 06:55 UTC, merged